---
title: "Data_wrangling"
author: "Veronica Liu"
date: "2024-09-17"
output: github_document
---
```{r setup, echo=FALSE, message=FALSE}

library(tidyverse)
library(readxl)
library(haven)
```



This document will show how to import data.

## Import thr FAS litters CSV
```{r}
litters_df = read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)
```


## Look at the dataset
```{r}
litters_df

head(litters_df)
tail(litters_df, 10)
```


##Learning accessment
```{r}
pups_df = read_csv("data/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)


pups_df
```

## Look at the read_csv option
```{r}
litters_df =
  read_csv(
    file = "data/FAS_litters.csv",
    skip = 2
  )
```

What about missing data

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("NA","",".")
  )

litters_df = janitor::clean_names(litters_df)

pull(litters_df, gd0_weight)
```

##Import an excel

```{r}
mlb_df = read_excel("data/mlb11.xlsx", sheet = "mlb11")
```

##Import SAS data
```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

